stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw
    outs:
      - data/prepared

  optimize:
    cmd: python src/optimize.py
    deps:
      - src/optimize.py
      - config/config.yaml
      - data/prepared